AdminBundle\Entity\User:
    itemOperations:
        users:
            method: 'GET'
            path: '/users'
        user:
            method: 'GET'
            path: '/user/{id}'
        status:
            method: 'PUT'
        special:
            route_name: 'user_status'