AdminBundle\Entity\User:
    itemOperations:
        users:
            method: 'GET'
            path: '/users'
        user:
            method: 'GET'
            path: '/user/{id}'
        status:
            method: 'PUT'
        validate:
            route_name: 'validate'
        user:
             method: 'POST'
             path: '/user'