admin:
    path:      /admin
    defaults:  { _controller: AdminBundle:Default:index }

login:
    path:      /admin/login
    defaults:  { _controller: AdminBundle:Default:login }

users:
    path:      /admin/users
    defaults:  { _controller: AdminBundle:Default:users }

logout:
    path:      /admin/logout
    defaults:  { _controller: AdminBundle:Default:logout }

delete:
    path:      /admin/users/delete{id}
    defaults:  
         _controller: AdminBundle:Default:delete 

modify:
    path:      /admin/users/modify
    defaults:  
         _controller: AdminBundle:Default:modify 

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional

status:
      path: 'api/user/{id}/status'
      methods:  ['GET']
      defaults:
          _controller: 'AdminBundle:Api:index'
          _api_resource_class: 'AdminBundle\Entity\User'
          _api_item_operation_name: 'status'
