admin:
    path:      /admin
    defaults:  { _controller: AdminBundle:Default:index }

login:
    path:      /admin/login
    defaults:  { _controller: AdminBundle:Default:login }

users:
    path:      /admin/users
    defaults:  { _controller: AdminBundle:Default:users }

logout:
    path:      /admin/logout
    defaults:  { _controller: AdminBundle:Default:logout }


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
