admin:
    path:      /admin
    defaults:  { _controller: AdminBundle:Default:index }

login:
    path:      /admin/login
    defaults:  { _controller: AdminBundle:Default:login }

users:
    path:      /admin/users
    defaults:  { _controller: AdminBundle:Default:users }

logout:
    path:      /admin/logout
    defaults:  { _controller: AdminBundle:Default:logout }

delete:
    path:      /admin/users/delete{id}
    defaults:  
         _controller: AdminBundle:Default:delete 

modify:
    path:      /admin/users/modify
    defaults:  
         _controller: AdminBundle:Default:modify 

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# API SYMFONY DE BASE
utilisateurs:
    path:      /utilisateurs
    defaults:  { _controller: AdminBundle:Api:utilisateurs }
utilisateurs_seul:
    path:      /utilisateurs/{id}
    defaults:  { _controller: AdminBundle:Api:utilisateur }
utilisateurs_seul_valid:
    path:      /utilisateurs/{id}/valid
    defaults:  { _controller: AdminBundle:Api:valid }
utilisateurs_seul_refuse:
    path:      /utilisateurs/{id}/refuse
    defaults:  { _controller: AdminBundle:Api:refuse }
utilisateurs_post:
    path:      /inscription
    defaults:  { _controller: AdminBundle:Api:postUtilisateurs }

# API PLATFORM

#api:
#    resource: '.'
#    type:     'api_platform'
#    prefix:   '/api' # Optional

#validate:
#      path: 'api/user/{id}/validate'
#      methods:  ['PUT']
#      defaults:
#          _controller: 'AdminBundle:Api:validate'
#          _api_resource_class: 'AdminBundle\Entity\User'
#          _api_item_operation_name: 'validate'
