admin:
    path:      /admin
    defaults:  { _controller: AdminBundle:Default:index }

login:
    path:      /admin/login
    defaults:  { _controller: AdminBundle:Default:login }

users:
    path:      /admin/users
    defaults:  { _controller: AdminBundle:Default:users }

logout:
    path:      /admin/logout
    defaults:  { _controller: AdminBundle:Default:logout }

delete:
    path:      /admin/users/delete{id}
    defaults:  
         _controller: AdminBundle:Default:delete 

modify:
    path:      /admin/users/modify
    defaults:  
         _controller: AdminBundle:Default:modify 

modifybase:
    path:      /admin/users/modifybase
    defaults:  
         _controller: AdminBundle:Default:modifybase 

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
